#!/bin/bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# Author: Jason Burman                                            #
# Script: host_uptime.sh                                          #
# Description: The purpose of this script is to login to hosts to #
#              check device uptime, hostname, ip address.         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

cat << "EOF"
 ____ ___         __  .__                 _________ .__                   __                 
|    |   \_______/  |_|__| _____   ____   \_   ___ \|  |__   ____   ____ |  | __ ___________ 
|    |   /\____ \   __\  |/     \_/ __ \  /    \  \/|  |  \_/ __ \_/ ___\|  |/ // __ \_  __ \
|    |  / |  |_> >  | |  |  Y Y  \  ___/  \     \___|   Y  \  ___/\  \___|    <\  ___/|  | \/
|______/  |   __/|__| |__|__|_|  /\___  >  \______  /___|  /\___  >\___  >__|_ \\___  >__|   
          |__|                 \/     \/          \/     \/     \/     \/     \/    \/       
          
hosts=~/uptime_hosts
username=root

for hosts in $(cat ~/uptime_hosts) ; do
 hostname=$(ssh "${username}@${hosts}" hostname)
 ip_addr=$(ssh "${username}@${hosts}" hostname -I)
 uptime=$(ssh "${username}@${hosts}" uptime)
 echo
 {
    echo "* Hostname:?$hostname"
    echo "* IP:?$ip_addr"
    echo "* uptime:?$uptime"
 } | column -s\? -t
 echo
done <"$hosts"
